name: .NET Core Tests

on:
  push:
    branches: [ "C#Migration" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Run tests with RunTests.sh
        run: |
          cd ./CargoHub  # Assuming the script is one directory below the current working directory
          chmod +x ../RunTests.sh  # Make sure the script is executable
          ./../RunTests.sh  # Execute the script
