name: Generate PlantUML Class Diagrams
on:
  push:
    branches:
        "v2"

jobs:
  plantuml-class-diagram:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Source
        uses: actions/checkout@v4

      # Step 2: Set up .NET 8.0 SDK (or newer) environment
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Use .NET 8.0 or newer

      - name: Install PlantUmlClassDiagramGenerator
        run: |
          dotnet tool install --global PlantUmlClassDiagramGenerator

      # Step 4: Generate PlantUML Diagrams
      - name: Generate PlantUML Diagrams
        run: |
          mkdir -p UML
          puml-gen ./CargoHub ./UML -dir -createAssociation -allInOne

      # Step 5: Convert PlantUML Diagrams to PNG
      - name: Convert UML Diagrams to PNG
        run: |
          # Install PlantUML CLI
          sudo apt-get update && sudo apt-get install -y default-jre graphviz
          # Convert all .puml files in UML directory to PNG
          for file in UML/*.puml; do
            plantuml -tpng "$file"
          done
          # Remove .puml files after conversion
          find UML -name "*.puml" -delete

      # Step 5: Commit and push UML diagrams
      - name: Commit and Push UML Diagrams
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ./UML
          git commit -m "Update UML diagrams"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}







