name: Auto PlantUML Class Diagram Generator

on:
  push:
    branches:
      - "v2"

  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java (PlantUML requires Java)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Install PlantUML generator tool
      - name: Install PlantUML Generator
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          npm install -g plantuml-generator

      # Step 4: Generate PlantUML diagrams
      - name: Generate PlantUML Class Diagram
        run: |
          mkdir -p generated_diagrams
          plantuml-generator ./src --output ./generated_diagrams/classes.puml

      # Step 5: Commit the generated diagram back to the repository (optional)
      - name: Commit Diagram
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./generated_diagrams
          git commit -m "Auto-generated PlantUML diagrams"
          git push