name: Auto PlantUML Class Diagram Generator

on:
  push:
    branches:
      - "v2"

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Create diagrams folder if not exists
        run: |
          mkdir -p diagrams

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg diagrams/*.puml






