name: CargoHub-Test

on:
  push:
    branches: [ "C#Migration" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        cache: true

    - name: Restore dependencies
      run: dotnet restore --use-lock-file

    - name: Build the project
      run: dotnet build CargoHub.csproj