name: CargoHub-Test

on:
  push:
    branches: [ "C#Migration" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List files
      run: ls -la

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        cache: true

    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: ./CargoHub

    - name: Build the project
      run: |
        echo "Starting dotnet build..."
        dotnet build CargoHub.csproj
        echo "Dotnet build completed successfully."
      working-directory: ./CargoHub

    - name: Debug Environment
      run: |
        echo Current shell: %COMSPEC%
        echo Runner OS: %RUNNER_OS%
        shell: cmd 
    - name: Run the project in new window
      run: start "" .\bin\Cargohub.exe
      working-directory: ./CargoHub
      shell: cmd

    - name: Test API
      run: dotnet test
      working-directory: ./CargoHub.Tests