name: CargoHub-Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        cache: false

    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: ./CargoHub

    - name: Build the project
      run: |
        dotnet build CargoHub.csproj
      working-directory: ./CargoHub

    - name: Run the project in new window
      run: dotnet run & # /bin/Cargohub.exe &
      working-directory: ./CargoHub 

    - name: Test API
      id: test-api
      run: bash RunTests.sh
      working-directory: ./CargoHub

    - name: Check test results
      if: failure()
      run: exit 1

    - name: Upload test run results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-run-results
        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/TestResults/test_results.trx"
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/CargoHub.Tests"

    - name: Check test results and report status
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const { context, github } = require('@actions/github');
          const testApiStatus = '${{ steps.test-api.outcome }}'; // Get the outcome of the Test API step

          const status = testApiStatus === 'success' ? 'success' : 'failure';
          const description = status === 'success' ? 'All tests passed!' : 'Some tests failed.';

          await github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: status,
            description: description,
            context: 'Test API Status'
          });

    - name: Fail workflow if tests failed
      if: failure()
      run: exit 1
