# name: CargoHub-Test

# on:
#   push:
#     branches: [ "C#Migration" ]

# jobs:
#   build:
#     #runs-on: ubuntu-latest
#     runs-on: self-hosted
#     steps:
#     - uses: actions/checkout@v4

#     - name: List files
#       run: ls -la

#     - name: Set up .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: '8.0'
#         cache: false

#     - name: Restore dependencies
#       run: dotnet restore --use-lock-file
#       working-directory: ./CargoHub

#     - name: Build the project
#       run: |
#         dotnet build CargoHub.csproj
#       working-directory: ./CargoHub

#     - name: Run the project in new window
#       run: /bin/Cargohub.exe &
#       working-directory: ./CargoHub

#     - name: Test API
#       run: bash RunTests.sh
#       working-directory: ./CargoHub
      