name: CargoHub-MigrateToServer

on:
  push:
    branches: [ "C#Migration" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: List files
      run: ls -la

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        cache: true

    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: ./CargoHub

    - name: Build the project
      run: |
        echo "Starting dotnet build..."
        dotnet build CargoHub.csproj
        echo "Dotnet build completed successfully."
      working-directory: ./CargoHub