
#runner on LINUX
name: CargoHub-MigrateToServer

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: ./CargoHub
    
    - name: Build the project 
      run: |
        dotnet build CargoHub.csproj
      working-directory: ./CargoHub

    # - name: Checkout repository
    #   uses: actions/checkout@v3

      #Set up SSH agent and add private key
    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
   
      #copy codebase to server
    - name: Copy codebase to server
      run: ssh ubuntu-1079726@145.24.223.236 "cd ~/ubuntu-1079726/CargoHub.NET/CargoHub; git checkout deploy; git pull"

      #restart API on server
    - name: restartstart API 
      run: |
        [[ $(pgrep -f "sudo -S nohup dotnet run --project /home/ubuntu-1079726/ubuntu-1079726/CargoHub.NET/CargoHub/CargoHub/CargoHub.csproj") ]] && kill $(pgrep -f "sudo -S nohup dotnet run --project /home/ubuntu-1079726/ubuntu-1079726/CargoHub.NET/CargoHub/CargoHub/CargoHub.csproj") || echo "Process not running"; 
        echo "${{secrets.SERVERPASSWORD}}" | sudo -S nohup dotnet run --project /home/ubuntu-1079726/ubuntu-1079726/CargoHub.NET/CargoHub/CargoHub/CargoHub.csproj > /home/ubuntu-1079726/ubuntu-1079726/CargoHubLog.log 2>&1 &

        
