name: CargoHub-Test

on:
  push:
    branches: [ "C#Migration" ]

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted # self-hosted (UTKU) is on windows
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        cache: true

    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: ./CargoHub

    - name: Build the project
      run: |
        dotnet build CargoHub.csproj
      working-directory: ./CargoHub

    # - name: Run the project in new window
    #   run: start /b /bin/Debug/net8.0/Cargohub.exe
    #   working-directory: ./CargoHub
    # tests should work without needing to start api
    - name: Test API
      run: bash RunTests.sh
      working-directory: ./CargoHub
      