name: CargoHub-Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
        cache: false

    - name: Restore dependencies
      run: dotnet restore --use-lock-file
      working-directory: ./CargoHub

    - name: Build the project
      run: |
        dotnet build CargoHub.csproj
      working-directory: ./CargoHub

    - name: Run the project in new window
      run: dotnet run & # /bin/Cargohub.exe &
      working-directory: ./CargoHub 

    - name: Test API
      id: test-api
      run: bash RunTests.sh
      working-directory: ./CargoHub

    - name: Check test results
      if: failure()
      run: exit 1

    - name: Upload test run results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-run-results
        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/TestResults/test_results.trx"
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/CargoHub.Tests"

  revert-change:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # check out the current and prior state
      - name: "Revert the commit that triggered this run, then push it to main"
        shell: bash
        run: |
          echo "Reverting ${{ github.sha }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert --no-edit ${{ github.sha }}
          git push origin main
